[package]
name = "twichcoin"
edition = "2024"         # edition = "legacy" to use legacy (pre-2024) Move
[addresses]
twichcoin = "0x0"
# license = ""           # e.g., "MIT", "GPL", "Apache 2.0"
# authors = ["..."]      # e.g., ["Joe Smith (joesmith@noemail.com)", "John Snow (johnsnow@noemail.com)"]

